import { BOT_SUBDIVISIONS } from './bot-regions-subdivisions';

export interface BotRegion {
  slug: string;
  name: string;
  username: string;
  country: string;
}

/** US states + countries + major state/province bots worldwide */
export const BOT_REGIONS: BotRegion[] = [
  // US states
  { slug: 'alabama', name: 'Alabama', username: 'AlabamaPulse', country: 'USA' },
  { slug: 'alaska', name: 'Alaska', username: 'AlaskaWire', country: 'USA' },
  { slug: 'arizona', name: 'Arizona', username: 'ArizonaNow', country: 'USA' },
  { slug: 'arkansas', name: 'Arkansas', username: 'ArkansasBeat', country: 'USA' },
  { slug: 'california', name: 'California', username: 'CaliViral', country: 'USA' },
  { slug: 'colorado', name: 'Colorado', username: 'ColoradoScope', country: 'USA' },
  { slug: 'connecticut', name: 'Connecticut', username: 'CTHeadlines', country: 'USA' },
  { slug: 'delaware', name: 'Delaware', username: 'DelawareDaily', country: 'USA' },
  { slug: 'florida', name: 'Florida', username: 'FloridaFlash', country: 'USA' },
  { slug: 'georgia', name: 'Georgia', username: 'GeorgiaGlobe', country: 'USA' },
  { slug: 'hawaii', name: 'Hawaii', username: 'HawaiiHype', country: 'USA' },
  { slug: 'idaho', name: 'Idaho', username: 'IdahoInsider', country: 'USA' },
  { slug: 'illinois', name: 'Illinois', username: 'ChicagoChronicle', country: 'USA' },
  { slug: 'indiana', name: 'Indiana', username: 'IndianaIntel', country: 'USA' },
  { slug: 'iowa', name: 'Iowa', username: 'IowaInsight', country: 'USA' },
  { slug: 'kansas', name: 'Kansas', username: 'KansasKronicle', country: 'USA' },
  { slug: 'kentucky', name: 'Kentucky', username: 'KentuckyKey', country: 'USA' },
  { slug: 'louisiana', name: 'Louisiana', username: 'LouisianaLive', country: 'USA' },
  { slug: 'maine', name: 'Maine', username: 'MaineMonitor', country: 'USA' },
  { slug: 'maryland', name: 'Maryland', username: 'MarylandMinute', country: 'USA' },
  { slug: 'massachusetts', name: 'Massachusetts', username: 'BostonBulletin', country: 'USA' },
  { slug: 'michigan', name: 'Michigan', username: 'MichiganMirror', country: 'USA' },
  { slug: 'minnesota', name: 'Minnesota', username: 'TwinCitiesTrend', country: 'USA' },
  { slug: 'mississippi', name: 'Mississippi', username: 'MississippiMemo', country: 'USA' },
  { slug: 'missouri', name: 'Missouri', username: 'MissouriMosaic', country: 'USA' },
  { slug: 'montana', name: 'Montana', username: 'MontanaMoment', country: 'USA' },
  { slug: 'nebraska', name: 'Nebraska', username: 'NebraskaNews', country: 'USA' },
  { slug: 'nevada', name: 'Nevada', username: 'VegasVortex', country: 'USA' },
  { slug: 'new-hampshire', name: 'New Hampshire', username: 'NHNow', country: 'USA' },
  { slug: 'new-jersey', name: 'New Jersey', username: 'JerseyJournal', country: 'USA' },
  { slug: 'new-mexico', name: 'New Mexico', username: 'SantaFeScope', country: 'USA' },
  { slug: 'new-york', name: 'New York', username: 'NYCNeural', country: 'USA' },
  { slug: 'north-carolina', name: 'North Carolina', username: 'CarolinaChronicle', country: 'USA' },
  { slug: 'north-dakota', name: 'North Dakota', username: 'DakotaDispatch', country: 'USA' },
  { slug: 'ohio', name: 'Ohio', username: 'OhioOracle', country: 'USA' },
  { slug: 'oklahoma', name: 'Oklahoma', username: 'OKOutlook', country: 'USA' },
  { slug: 'oregon', name: 'Oregon', username: 'PortlandPulse', country: 'USA' },
  { slug: 'pennsylvania', name: 'Pennsylvania', username: 'PhillyFlash', country: 'USA' },
  { slug: 'rhode-island', name: 'Rhode Island', username: 'RhodeRadar', country: 'USA' },
  { slug: 'south-carolina', name: 'South Carolina', username: 'PalmettoPost', country: 'USA' },
  { slug: 'south-dakota', name: 'South Dakota', username: 'SiouxSignal', country: 'USA' },
  { slug: 'tennessee', name: 'Tennessee', username: 'NashvilleNow', country: 'USA' },
  { slug: 'texas', name: 'Texas', username: 'TexasTrendline', country: 'USA' },
  { slug: 'utah', name: 'Utah', username: 'UtahUpdate', country: 'USA' },
  { slug: 'vermont', name: 'Vermont', username: 'VermontVoice', country: 'USA' },
  { slug: 'virginia', name: 'Virginia', username: 'VirginiaVibe', country: 'USA' },
  { slug: 'washington', name: 'Washington', username: 'SeattleScope', country: 'USA' },
  { slug: 'west-virginia', name: 'West Virginia', username: 'WVWatch', country: 'USA' },
  { slug: 'wisconsin', name: 'Wisconsin', username: 'WisconsinWire', country: 'USA' },
  { slug: 'wyoming', name: 'Wyoming', username: 'WyomingWave', country: 'USA' },
  { slug: 'washington-dc', name: 'Washington D.C.', username: 'DCDispatch', country: 'USA' },
  { slug: 'puerto-rico', name: 'Puerto Rico', username: 'SanJuanSignal', country: 'USA' },
  // Countries & global cities
  { slug: 'argentina', name: 'Argentina', username: 'BuenosAiresBeat', country: 'Argentina' },
  { slug: 'australia', name: 'Australia', username: 'SydneyScope', country: 'Australia' },
  { slug: 'austria', name: 'Austria', username: 'ViennaViral', country: 'Austria' },
  { slug: 'bangladesh', name: 'Bangladesh', username: 'DhakaDaily', country: 'Bangladesh' },
  { slug: 'belgium', name: 'Belgium', username: 'BrusselsBrief', country: 'Belgium' },
  { slug: 'brazil', name: 'Brazil', username: 'RioRadar', country: 'Brazil' },
  { slug: 'canada', name: 'Canada', username: 'TorontoTrend', country: 'Canada' },
  { slug: 'chile', name: 'Chile', username: 'SantiagoSignal', country: 'Chile' },
  { slug: 'china', name: 'China', username: 'ShanghaiScope', country: 'China' },
  { slug: 'colombia', name: 'Colombia', username: 'BogotaBulletin', country: 'Colombia' },
  { slug: 'czechia', name: 'Czechia', username: 'PraguePulse', country: 'Czechia' },
  { slug: 'denmark', name: 'Denmark', username: 'CopenhagenChron', country: 'Denmark' },
  { slug: 'egypt', name: 'Egypt', username: 'CairoChronicle', country: 'Egypt' },
  { slug: 'ethiopia', name: 'Ethiopia', username: 'AddisAlert', country: 'Ethiopia' },
  { slug: 'finland', name: 'Finland', username: 'HelsinkiHype', country: 'Finland' },
  { slug: 'france', name: 'France', username: 'ParisPulse', country: 'France' },
  { slug: 'germany', name: 'Germany', username: 'BerlinBeat', country: 'Germany' },
  { slug: 'ghana', name: 'Ghana', username: 'AccraAlert', country: 'Ghana' },
  { slug: 'greece', name: 'Greece', username: 'AthensAtlas', country: 'Greece' },
  { slug: 'india', name: 'India', username: 'MumbaiMirror', country: 'India' },
  { slug: 'indonesia', name: 'Indonesia', username: 'JakartaJournal', country: 'Indonesia' },
  { slug: 'iran', name: 'Iran', username: 'TehranTrend', country: 'Iran' },
  { slug: 'iraq', name: 'Iraq', username: 'BaghdadBrief', country: 'Iraq' },
  { slug: 'ireland', name: 'Ireland', username: 'DublinDispatch', country: 'Ireland' },
  { slug: 'israel', name: 'Israel', username: 'TelAvivTimes', country: 'Israel' },
  { slug: 'italy', name: 'Italy', username: 'RomeRadar', country: 'Italy' },
  { slug: 'japan', name: 'Japan', username: 'TokyoTrend', country: 'Japan' },
  { slug: 'kenya', name: 'Kenya', username: 'NairobiNow', country: 'Kenya' },
  { slug: 'malaysia', name: 'Malaysia', username: 'KualaScope', country: 'Malaysia' },
  { slug: 'mexico', name: 'Mexico', username: 'MexicoMetro', country: 'Mexico' },
  { slug: 'morocco', name: 'Morocco', username: 'CasablancaChron', country: 'Morocco' },
  { slug: 'netherlands', name: 'Netherlands', username: 'AmsterdamAlert', country: 'Netherlands' },
  { slug: 'new-zealand', name: 'New Zealand', username: 'AucklandAtlas', country: 'New Zealand' },
  { slug: 'nigeria', name: 'Nigeria', username: 'LagosLive', country: 'Nigeria' },
  { slug: 'norway', name: 'Norway', username: 'OsloOracle', country: 'Norway' },
  { slug: 'pakistan', name: 'Pakistan', username: 'KarachiKey', country: 'Pakistan' },
  { slug: 'peru', name: 'Peru', username: 'LimaLens', country: 'Peru' },
  { slug: 'philippines', name: 'Philippines', username: 'ManilaMinute', country: 'Philippines' },
  { slug: 'poland', name: 'Poland', username: 'WarsawWire', country: 'Poland' },
  { slug: 'portugal', name: 'Portugal', username: 'LisbonLive', country: 'Portugal' },
  { slug: 'qatar', name: 'Qatar', username: 'DohaDispatch', country: 'Qatar' },
  { slug: 'romania', name: 'Romania', username: 'BucharestBeat', country: 'Romania' },
  { slug: 'russia', name: 'Russia', username: 'MoscowMirror', country: 'Russia' },
  { slug: 'saudi-arabia', name: 'Saudi Arabia', username: 'RiyadhRadar', country: 'Saudi Arabia' },
  { slug: 'singapore', name: 'Singapore', username: 'SingaporeScope', country: 'Singapore' },
  { slug: 'south-africa', name: 'South Africa', username: 'JoburgJournal', country: 'South Africa' },
  { slug: 'south-korea', name: 'South Korea', username: 'SeoulSignal', country: 'South Korea' },
  { slug: 'spain', name: 'Spain', username: 'MadridMetro', country: 'Spain' },
  { slug: 'sweden', name: 'Sweden', username: 'StockholmScope', country: 'Sweden' },
  { slug: 'switzerland', name: 'Switzerland', username: 'ZurichZone', country: 'Switzerland' },
  { slug: 'taiwan', name: 'Taiwan', username: 'TaipeiTrend', country: 'Taiwan' },
  { slug: 'thailand', name: 'Thailand', username: 'BangkokBeat', country: 'Thailand' },
  { slug: 'turkey', name: 'Turkey', username: 'IstanbulIntel', country: 'Turkey' },
  { slug: 'uae', name: 'UAE', username: 'DubaiDaily', country: 'UAE' },
  { slug: 'uk', name: 'United Kingdom', username: 'LondonLens', country: 'UK' },
  { slug: 'ukraine', name: 'Ukraine', username: 'KyivKey', country: 'Ukraine' },
  { slug: 'hong-kong', name: 'Hong Kong', username: 'HKHeadlines', country: 'China' },
  { slug: 'vietnam', name: 'Vietnam', username: 'HanoiHype', country: 'Vietnam' },
  ...BOT_SUBDIVISIONS,
];
