import { BotRegion } from './bot-regions';

/** State / province level bots beyond US (merged into seed list). */
export const BOT_SUBDIVISIONS: BotRegion[] = [
  // India — states & union territories (Bollywood + regional news)
  { slug: 'in-andhra-pradesh', name: 'Andhra Pradesh', username: 'APPulse', country: 'India' },
  { slug: 'in-arunachal-pradesh', name: 'Arunachal Pradesh', username: 'ArunachalAlert', country: 'India' },
  { slug: 'in-assam', name: 'Assam', username: 'AssamScope', country: 'India' },
  { slug: 'in-bihar', name: 'Bihar', username: 'BiharBeat', country: 'India' },
  { slug: 'in-chhattisgarh', name: 'Chhattisgarh', username: 'CGChronicle', country: 'India' },
  { slug: 'in-goa', name: 'Goa', username: 'GoaGlobe', country: 'India' },
  { slug: 'in-gujarat', name: 'Gujarat', username: 'GujaratGrid', country: 'India' },
  { slug: 'in-haryana', name: 'Haryana', username: 'HaryanaHype', country: 'India' },
  { slug: 'in-himachal-pradesh', name: 'Himachal Pradesh', username: 'HimachalHeadlines', country: 'India' },
  { slug: 'in-jharkhand', name: 'Jharkhand', username: 'JharkhandJournal', country: 'India' },
  { slug: 'in-karnataka', name: 'Karnataka', username: 'KarnatakaKey', country: 'India' },
  { slug: 'in-kerala', name: 'Kerala', username: 'KeralaKronicle', country: 'India' },
  { slug: 'in-madhya-pradesh', name: 'Madhya Pradesh', username: 'MPMirror', country: 'India' },
  { slug: 'in-maharashtra', name: 'Maharashtra', username: 'MahaMetro', country: 'India' },
  { slug: 'in-manipur', name: 'Manipur', username: 'ManipurMinute', country: 'India' },
  { slug: 'in-meghalaya', name: 'Meghalaya', username: 'MeghalayaMemo', country: 'India' },
  { slug: 'in-mizoram', name: 'Mizoram', username: 'MizoramMonitor', country: 'India' },
  { slug: 'in-nagaland', name: 'Nagaland', username: 'NagalandNow', country: 'India' },
  { slug: 'in-odisha', name: 'Odisha', username: 'OdishaOracle', country: 'India' },
  { slug: 'in-punjab', name: 'Punjab', username: 'PunjabPulse', country: 'India' },
  { slug: 'in-rajasthan', name: 'Rajasthan', username: 'RajasthanRadar', country: 'India' },
  { slug: 'in-sikkim', name: 'Sikkim', username: 'SikkimSignal', country: 'India' },
  { slug: 'in-tamil-nadu', name: 'Tamil Nadu', username: 'TamilTrend', country: 'India' },
  { slug: 'in-telangana', name: 'Telangana', username: 'TelanganaTimes', country: 'India' },
  { slug: 'in-tripura', name: 'Tripura', username: 'TripuraToday', country: 'India' },
  { slug: 'in-uttar-pradesh', name: 'Uttar Pradesh', username: 'UPUpdate', country: 'India' },
  { slug: 'in-uttarakhand', name: 'Uttarakhand', username: 'UKDDispatch', country: 'India' },
  { slug: 'in-west-bengal', name: 'West Bengal', username: 'BengalBulletin', country: 'India' },
  { slug: 'in-delhi', name: 'Delhi', username: 'DelhiDaily', country: 'India' },
  { slug: 'in-jammu-kashmir', name: 'Jammu and Kashmir', username: 'JKJournal', country: 'India' },
  // Canada — provinces & territories
  { slug: 'ca-ontario', name: 'Ontario', username: 'OntarioOracle', country: 'Canada' },
  { slug: 'ca-quebec', name: 'Quebec', username: 'QuebecQuest', country: 'Canada' },
  { slug: 'ca-british-columbia', name: 'British Columbia', username: 'BCBeat', country: 'Canada' },
  { slug: 'ca-alberta', name: 'Alberta', username: 'AlbertaAlert', country: 'Canada' },
  { slug: 'ca-manitoba', name: 'Manitoba', username: 'ManitobaMemo', country: 'Canada' },
  { slug: 'ca-saskatchewan', name: 'Saskatchewan', username: 'SaskScope', country: 'Canada' },
  { slug: 'ca-nova-scotia', name: 'Nova Scotia', username: 'NovaNow', country: 'Canada' },
  { slug: 'ca-new-brunswick', name: 'New Brunswick', username: 'NBNews', country: 'Canada' },
  { slug: 'ca-newfoundland', name: 'Newfoundland and Labrador', username: 'NLLens', country: 'Canada' },
  { slug: 'ca-prince-edward-island', name: 'Prince Edward Island', username: 'PEIPulse', country: 'Canada' },
  // Australia — states & territories
  { slug: 'au-nsw', name: 'New South Wales', username: 'NSWNow', country: 'Australia' },
  { slug: 'au-victoria', name: 'Victoria', username: 'VictoriaViral', country: 'Australia' },
  { slug: 'au-queensland', name: 'Queensland', username: 'QLDQuest', country: 'Australia' },
  { slug: 'au-western-australia', name: 'Western Australia', username: 'WAWire', country: 'Australia' },
  { slug: 'au-south-australia', name: 'South Australia', username: 'SAScope', country: 'Australia' },
  { slug: 'au-tasmania', name: 'Tasmania', username: 'TasTrend', country: 'Australia' },
  // UK — nations
  { slug: 'uk-england', name: 'England', username: 'EnglandEdge', country: 'UK' },
  { slug: 'uk-scotland', name: 'Scotland', username: 'ScotlandScope', country: 'UK' },
  { slug: 'uk-wales', name: 'Wales', username: 'WalesWire', country: 'UK' },
  { slug: 'uk-northern-ireland', name: 'Northern Ireland', username: 'NINews', country: 'UK' },
];
