/** Google News locale codes per bot region slug */
export const NEWS_LOCALE: Record<string, { gl: string; hl: string }> = {
  argentina: { gl: 'AR', hl: 'es-419' },
  australia: { gl: 'AU', hl: 'en-AU' },
  austria: { gl: 'AT', hl: 'de' },
  bangladesh: { gl: 'BD', hl: 'en-BD' },
  belgium: { gl: 'BE', hl: 'nl-BE' },
  brazil: { gl: 'BR', hl: 'pt-BR' },
  canada: { gl: 'CA', hl: 'en-CA' },
  chile: { gl: 'CL', hl: 'es-419' },
  china: { gl: 'CN', hl: 'zh-CN' },
  colombia: { gl: 'CO', hl: 'es-419' },
  czechia: { gl: 'CZ', hl: 'cs' },
  denmark: { gl: 'DK', hl: 'da' },
  egypt: { gl: 'EG', hl: 'ar' },
  ethiopia: { gl: 'ET', hl: 'en' },
  finland: { gl: 'FI', hl: 'fi' },
  france: { gl: 'FR', hl: 'fr' },
  germany: { gl: 'DE', hl: 'de' },
  ghana: { gl: 'GH', hl: 'en-GH' },
  greece: { gl: 'GR', hl: 'el' },
  'hong-kong': { gl: 'HK', hl: 'en-HK' },
  india: { gl: 'IN', hl: 'en-IN' },
  indonesia: { gl: 'ID', hl: 'id' },
  iran: { gl: 'IR', hl: 'fa' },
  iraq: { gl: 'IQ', hl: 'ar' },
  ireland: { gl: 'IE', hl: 'en-IE' },
  israel: { gl: 'IL', hl: 'he' },
  italy: { gl: 'IT', hl: 'it' },
  japan: { gl: 'JP', hl: 'ja' },
  kenya: { gl: 'KE', hl: 'en-KE' },
  malaysia: { gl: 'MY', hl: 'en-MY' },
  mexico: { gl: 'MX', hl: 'es-419' },
  morocco: { gl: 'MA', hl: 'fr' },
  netherlands: { gl: 'NL', hl: 'nl' },
  'new-zealand': { gl: 'NZ', hl: 'en-NZ' },
  nigeria: { gl: 'NG', hl: 'en-NG' },
  norway: { gl: 'NO', hl: 'no' },
  pakistan: { gl: 'PK', hl: 'en-PK' },
  peru: { gl: 'PE', hl: 'es-419' },
  philippines: { gl: 'PH', hl: 'en-PH' },
  poland: { gl: 'PL', hl: 'pl' },
  portugal: { gl: 'PT', hl: 'pt-PT' },
  qatar: { gl: 'QA', hl: 'ar' },
  romania: { gl: 'RO', hl: 'ro' },
  russia: { gl: 'RU', hl: 'ru' },
  'saudi-arabia': { gl: 'SA', hl: 'ar' },
  singapore: { gl: 'SG', hl: 'en-SG' },
  'south-africa': { gl: 'ZA', hl: 'en-ZA' },
  'south-korea': { gl: 'KR', hl: 'ko' },
  spain: { gl: 'ES', hl: 'es' },
  sweden: { gl: 'SE', hl: 'sv' },
  switzerland: { gl: 'CH', hl: 'de' },
  taiwan: { gl: 'TW', hl: 'zh-TW' },
  thailand: { gl: 'TH', hl: 'th' },
  turkey: { gl: 'TR', hl: 'tr' },
  uae: { gl: 'AE', hl: 'ar' },
  uk: { gl: 'GB', hl: 'en-GB' },
  ukraine: { gl: 'UA', hl: 'uk' },
  vietnam: { gl: 'VN', hl: 'vi' },
};

export const US_LOCALE = { gl: 'US', hl: 'en-US' };

export function localeForSlug(slug: string, country: string) {
  if (country === 'USA') return US_LOCALE;
  return NEWS_LOCALE[slug] ?? { gl: 'US', hl: 'en-US' };
}
